### ISSUE TITLE
How does one use this?

### ISSUE THREAD

**Issue by riotrah** [iLLeniumStudios/awesome-list-generator#1]
Thanks for this. 
I hope I got the right idea, but this appears to be a tool for generating the kind of Awesome lists one sees all around GitHub, right? 

If so, that's great - I have a couple of different topics that I feel are under served in the GitHub community. However, despite briefly looking in the dockerfile and a couple of files, I feel like I might be missing some kind of obvious explanation on how to use this.

Either way, thanks again

**Comment by TheiLLeniumStudios** [comment]
Hi. Thank you for your interest in the project. Its not documented at the moment but my motivation of developing this was to create an awesome list of FiveM resources. If you'd like to use this project for your own lists, you can take a look at https://github.com/iLLeniumStudios/awesome-fivem

This includes a `config.yaml` file that awesome-list-generator takes as an input and it runs every 24 hours using a simple Github action: https://github.com/iLLeniumStudios/awesome-fivem/blob/main/.github/workflows/update-readme.yaml

It should give you an idea of how you can use this tool

**Comment by riotrah** [comment]
Awesome thanks!
